apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-tomcat-internal-registry
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pwr-demo/person:1.0
  type: image 
