apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clear-buildah-repo
spec:
  params:
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string
  steps :
    - name: buildah-remove-images
      command:
        - buildah
        - rmi
        - '-a'
        - '-f'
        - '--storage-driver=$(params.STORAGE_DRIVER)'
      image: registry.redhat.io/rhel8/buildah:8.7-5
      resources: {}
      volumeMounts:
        - name: pipeline-cache
          mountPath: /var/lib/containers
  volumes:
    - name: pipeline-cache
      emptyDir: {}
      #persistentVolumeClaim:
      #  claimName: pipeline-task-cache-pvc