FROM registry.redhat.io/jboss-webserver-5/jws57-openjdk11-openshift-rhel8:5.7.0-6

LABEL "io.openshift.s2i.build.image"="registry.redhat.io/jboss-webserver-5/jws57-openjdk11-openshift-rhel8:5.7.0-6" \
      "io.openshift.s2i.build.source-location"="."

USER root

COPY app/pom.xml /tmp/src/pom.xml
COPY app/src /tmp/src/src

# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/src 

USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/local/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/local/s2i/run

# JWS User
USER 185





